#!/usr/bin/env python3
"""Generate a deterministic SHA-256 manifest for frozen scientific fixtures.

Publication infrastructure only. This does not validate physical models or measurements.
The authoritative fixture membership and Git blob identities come from
provenance/scientific-fixtures-v3.10.json. This tool verifies those identities first,
then emits independent SHA-256 digests and byte lengths in a deterministic JSON form.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from pathlib import Path

DEFAULT_MANIFEST = "provenance/scientific-fixtures-v3.10.json"


def git(root: Path, *args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=root, text=True).strip()


def build_manifest(root: Path, source_manifest: Path) -> dict:
    source = json.loads(source_manifest.read_text(encoding="utf-8"))
    files = source["files"]
    paths = [item["path"] for item in files]
    if len(paths) != len(set(paths)):
        raise SystemExit("ATTESTATION_FAIL duplicate paths in source manifest")

    anchor = source["anchor_commit"]
    try:
        subprocess.run(
            ["git", "merge-base", "--is-ancestor", anchor, "HEAD"],
            cwd=root,
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"ATTESTATION_FAIL anchor {anchor} is not an ancestor of HEAD") from exc

    out_files = []
    for item in sorted(files, key=lambda x: x["path"]):
        rel = item["path"]
        path = root / rel
        if not path.is_file():
            raise SystemExit(f"ATTESTATION_FAIL missing fixture {rel}")
        actual_blob = git(root, "hash-object", "--", rel)
        expected_blob = item["git_blob_sha1"]
        if actual_blob != expected_blob:
            raise SystemExit(
                f"ATTESTATION_FAIL {rel}: git blob {actual_blob} != frozen {expected_blob}"
            )
        payload = path.read_bytes()
        out_files.append(
            {
                "path": rel,
                "bytes": len(payload),
                "git_blob_sha1": actual_blob,
                "sha256": hashlib.sha256(payload).hexdigest(),
                "role": item["role"],
            }
        )

    return {
        "schema_version": 1,
        "manifest_version": "v3.11",
        "status": "PUBLICATION_INFRASTRUCTURE_ONLY",
        "source_manifest": str(source_manifest.relative_to(root)),
        "source_manifest_version": source["manifest_version"],
        "anchor_commit": anchor,
        "algorithm": "sha256",
        "files": out_files,
    }


def canonical_json(obj: dict) -> str:
    return json.dumps(obj, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None, help="Repository root; defaults to tool parent.")
    ap.add_argument("--source-manifest", default=DEFAULT_MANIFEST)
    ap.add_argument("--output", default=None)
    ap.add_argument("--check", default=None, help="Compare generated bytes with an existing manifest.")
    args = ap.parse_args()

    root = Path(args.root).resolve() if args.root else Path(__file__).resolve().parents[1]
    source_manifest = root / args.source_manifest
    built = build_manifest(root, source_manifest)
    text = canonical_json(built)

    if args.check:
        existing = (root / args.check).read_text(encoding="utf-8")
        if existing != text:
            raise SystemExit(f"ATTESTATION_FAIL generated manifest differs from {args.check}")

    if args.output:
        out = Path(args.output)
        if not out.is_absolute():
            out = root / out
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
