#!/usr/bin/env python3
"""Independent arithmetic packet for the v3.50 voltage-only useful-work bound.

Standard library only. No experimental result is generated by this script.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent
INPUT = HERE / "voltage_only_useful_work_bound_v3_50.json"
TOL = 1e-12


def direct_gain(delta_v: float, voc0: float) -> float:
    if delta_v < 0 or voc0 <= 0:
        raise ValueError("delta_v must be nonnegative and voc0 positive")
    return delta_v / voc0


def ratio_gain(delta_v: float, voc0: float) -> float:
    """Independent path from P1/P0 with Jsc and FF cancelling."""
    if delta_v < 0 or voc0 <= 0:
        raise ValueError("delta_v must be nonnegative and voc0 positive")
    return (voc0 + delta_v) / voc0 - 1.0


def threshold_voc(delta_v: float, target_gain: float) -> float:
    if delta_v < 0 or target_gain <= 0:
        raise ValueError("delta_v must be nonnegative and target_gain positive")
    return delta_v / target_gain


def main() -> None:
    data = json.loads(INPUT.read_text())
    delta = float(data["primary_source"]["source_value"]["delta_voc_V"])
    target = float(data["project_decision_rule"]["minimum_relative_stabilized_pmax_gain"])
    expected = data["expected"]

    vcrit = threshold_voc(delta, target)
    assert math.isclose(vcrit, expected["voc0_max_for_5pct_from_20mV_V"], rel_tol=0.0, abs_tol=TOL)

    # Independent derivation: direct ΔV/V and explicit P1/P0 ratio must agree.
    for voc0 in (0.4, 0.8, 0.9, 1.0):
        a = direct_gain(delta, voc0)
        b = ratio_gain(delta, voc0)
        assert math.isclose(a, b, rel_tol=0.0, abs_tol=TOL)

    # Boundary case: exactly 0.4 V with +20 mV gives exactly the 5% target.
    assert math.isclose(direct_gain(delta, vcrit), target, rel_tol=0.0, abs_tol=TOL)

    # Negative/control case frozen in JSON: 0.8 V + 20 mV is only 2.5%.
    neg = expected["negative_fixture"]
    gneg = direct_gain(float(neg["delta_voc_V"]), float(neg["voc0_V"]))
    assert math.isclose(gneg, float(neg["voltage_only_relative_gain"]), rel_tol=0.0, abs_tol=TOL)
    assert (gneg >= target) is bool(neg["passes_5pct_gate"])

    # Limiting cases and normalization.
    assert direct_gain(0.0, 0.8) == 0.0
    assert direct_gain(delta * 100.0, 0.8 * 100.0) == direct_gain(delta, 0.8)

    # Sensitivity is analytic and monotonic in ΔV.
    last = -math.inf
    for row in expected["sensitivity"]:
        value = threshold_voc(float(row["delta_voc_V"]), target)
        assert math.isclose(value, float(row["voc0_max_V"]), rel_tol=0.0, abs_tol=TOL)
        assert value > last
        last = value

    print(json.dumps({
        "status": "PASS",
        "claim_class": data["claim_class"],
        "delta_voc_V": delta,
        "target_gain": target,
        "voc0_max_for_voltage_only_target_V": vcrit,
        "negative_fixture_gain": gneg,
        "tolerance": TOL,
    }, sort_keys=True))


if __name__ == "__main__":
    main()
